version: '3.8'

services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
     - jenkins-home:/var/jenkins_home

volumes:
  jenkins-home:
