services:
  portainer:
    image: portainer/portainer-ce
    container_name: "portainer"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

volumes:
  portainer-data:
